# Generated by Django 3.0.8 on 2020-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0003_auto_20200808_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='land'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='image1',
            field=models.ImageField(default='default.jpg', upload_to='warehouses'),
        ),
    ]
